import React from "react";
import Header from "../Header";
import Subfooter from "../Subfooter";
import Subheader from "../Subheader";
const Termofuse = () => {
  return (
    <>
      <Header />
      <Subheader />

      <div className="wrap-28">
        <div className="container">
          <div className="row">
            <div className="col-md-12 mt-5">
              <h6>Flipkart Terms of Use</h6>
            </div>
            <div className="bin-30 mt-4">
              <p>
                This document is an electronic record in terms of Information
                Technology Act, 2000 and rules there under as applicable and the
                amended provisions pertaining to electronic records in various
                statutes as amended by the Information Technology Act, 2000.
                This electronic record is generated by a computer system and
                does not require any physical or digital signatures.
              </p>
              <p>
                This document is published in accordance with the provisions of
                Rule 3 (1) of the Information Technology (Intermediaries
                guidelines) Rules, 2011 that require publishing the rules and
                regulations, privacy policy and Terms of Use for access or usage
                of domain name [www.flipkart.com][www.flipkart.com] (“Website”),
                including the related mobile site and mobile application
                (hereinafter referred to as “Platform”)
              </p>

              <p>
                The Platform is owned by Flipkart Internet Private Limited a
                company incorporated under the Companies Act, 1956 with its
                registered office at Buildings Alyssa, Begonia & Clover, Embassy
                Tech Village, Outer Ring Road, Devarabeesanahalli Village,
                Bengaluru – 560103, Karnataka, India and its branch offices at
                2nd Floor, Block F (Flora), Embassy Tech Village, Outer Ring
                Road, Devarabeesanahalli Village, Bengaluru-560103, Karnataka,
                India and; 447/C, 12th Main, 4th Block, Koramangala,
                Bengaluru-560034, Karnataka, India (hereinafter referred to as
                "Flipkart").
              </p>
              <p>
                For the purpose of these Terms of Use, wherever the context so
                requires "You" or "User" shall mean any natural or legal person
                who has agreed to become a buyer on the Platform by providing
                Registration Data while registering on the Platform as
                Registered User using the computer systems. Flipkart allows the
                User to surf the Platform or making purchases without
                registering on the Platform. The term "We", "Us", "Our" shall
                mean Flipkart Internet Private Limited.
              </p>
              <p>
                When You use any of the services provided by Us through the
                Platform, including but not limited to, (e.g. Product Reviews,
                Seller Reviews), You will be subject to the rules, guidelines,
                policies, terms, and conditions applicable to such service, and
                they shall be deemed to be incorporated into this Terms of Use
                and shall be considered as part and parcel of this Terms of Use.
                We reserve the right, at Our sole discretion, to change, modify,
                add or remove portions of these Terms of Use, at any time
                without any prior written notice to You. It is Your
                responsibility to review these Terms of Use periodically for
                updates / changes. Your continued use of the Platform following
                the posting of changes will mean that You accept and agree to
                the revisions. As long as You comply with these Terms of Use, We
                grant You a personal, non-exclusive, non-transferable, limited
                privilege to enter and use the Platform.
              </p>
              <p>
                ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR
                AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF
                USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE
                PROCEEDING. By impliedly or expressly accepting these Terms of
                Use, You also accept and agree to be bound by Flipkart Policies
                ((including but not limited to Privacy Policy available at
                Privacy) as amended from time to time.
              </p>
            </div>
            <div className="bin-30 mt-4">
              <h5>Membership Eligibility</h5>
              <p>
                Transaction on the Platform is available only to persons who can
                form legally binding contracts under Indian Contract Act, 1872.
                Persons who are "incompetent to contract" within the meaning of
                the Indian Contract Act, 1872 including un-discharged insolvents
                etc. are not eligible to use the Platform. If you are a minor
                i.e. under the age of 18 years, you may use the Platform or
                access content on the Platform only under the supervision and
                prior consent/ permission of a parent ormlegal guardian.
              </p>
              <p>
                As a minor if you wish to transact on the Platform, such
                transaction on the Platform may be made by your legal guardian
                or parents. Flipkart reserves the right to terminate your
                membership and / or refuse to provide you with access to the
                Platform if it is brought to Flipkart's notice or if it is
                discovered that You are under the age of 18 years and
                transacting on the Platform.
              </p>
            </div>
            <div className="bin-30 mt-4">
              <h5>Your Account and Registration Obligations</h5>
              <p>
                If You use the Platform, You shall be responsible for
                maintaining the confidentiality of your Display Name and
                Password and You shall be responsible for all activities that
                occur under your Display Name and Password. You agree that if
                You provide any information that is untrue, inaccurate, not
                current or incomplete or We have reasonable grounds to suspect
                that such information is untrue, inaccurate, not current or
                incomplete, or not in accordance with the this Terms of Use, We
                shall have the right to indefinitely suspend or terminate or
                block access of your membership on the Platform and refuse to
                provide You with access to the Platform.
              </p>
              <p>
                Your mobile phone number and/or e-mail address is treated as
                Your primary identifier on the Platform. It is your
                responsibility to ensure that Your mobile phone number and your
                email address is up to date on the Platform at all times. You
                agree to notify Us promptly if your mobile phone number or
                e-mail address changes by updating the same on the Platform
                through a onetime password verification.
              </p>
              <p>
                You agree that Flipkart shall not be liable or responsible for
                the activities or consequences of use or misuse of any
                information that occurs under your Account in cases, including,
                where You have failed to update Your revised mobile phone number
                and/or e-mail address on the Website Platform.
              </p>
              <p>
                If You share or allow others to have access to Your account on
                the Platform (“Account”), by creating separate profiles under
                Your Account, or otherwise, they will be able to view and access
                Your Account information. You shall be solely liable and
                responsible for all the activities undertaken under Your
                Account, and any consequences therefrom.
              </p>
            </div>
            <div className="bin-30 mt-4">
              <h5>Communications</h5>
              <p>
                When You use the Platform or send emails or other data,
                information or communication to us, You agree and understand
                that You are communicating with Us through electronic records
                and You consent to receive communications via electronic records
                from Us periodically and as and when required. We may
                communicate with you by email or by such other mode of
                communication, electronic or otherwise.
              </p>
            </div>
            <div className="bin-30 mt-4">
              <h5>Platform for Transaction and Communication</h5>
              <p>
                The Platform is a platform that Users utilize to meet and
                interact with one another for their transactions. Flipkart is
                not and cannot be a party to or control in any manner any
                transaction between the Platform's Users.
              </p>
              <p>Henceforward</p>
              <ul>
                <li>
                  <p>
                    All commercial/contractual terms are offered by and agreed
                    to between Buyers and Sellers alone. The
                    commercial/contractual terms include without limitation
                    price, shipping costs, payment methods, payment terms, date,
                    period and mode of delivery, warranties related to products
                    and services and after sales services related to products
                    and services. Flipkart does not have any control or does not
                    determine or advise or in any way involve itself in the
                    offering or acceptance of such commercial/contractual terms
                    between the Buyers and Sellers. All discounts, offers
                    (including exchange offers) are by the Seller/Brand and not
                    by Flipkart.
                  </p>
                </li>
                <li>
                  <p>
                    Placement of order by a Buyer with Seller on the Platform is
                    an offer to buy the product(s) in the order by the Buyer to
                    the Seller and it shall not be construed as Seller's
                    acceptance of Buyer's offer to buy the product(s) ordered.
                    The Seller retains the right to cancel any such order placed
                    by the Buyer, at its sole discretion and the Buyer shall be
                    intimated of the same by way of an email/SMS. Any
                    transaction price paid by Buyer in case of such cancellation
                    by Seller, shall be refunded to the Buyer. Further, the
                    Seller may cancel an order wherein the quantities exceed the
                    typical individual consumption. This applies both to the
                    number of products ordered within a single order and the
                    placing of several orders for the same product where the
                    individual orders comprise a quantity that exceeds the
                    typical individual consumption. What comprises a typical
                    individual's consumption quantity limit shall be based on
                    various factors and at the sole discretion of the Seller and
                    may vary from individual to individual.
                  </p>
                </li>
                <li>
                  <p>
                    Flipkart does not make any representation or Warranty as to
                    specifics (such as quality, value, salability, etc) of the
                    products or services proposed to be sold or offered to be
                    sold or purchased on the Platform. Flipkart does not
                    implicitly or explicitly support or endorse the sale or
                    purchase of any products or services on the Platform.
                    Flipkart accepts no liability for any errors or omissions,
                    whether on behalf of itself or third parties.
                  </p>
                </li>
                <li>
                  <p>
                    Flipkart is not responsible for any non-performance or
                    breach of any contract entered into between Buyers and
                    Sellers. Flipkart cannot and does not guarantee that the
                    concerned Buyers and/or Sellers will perform any transaction
                    concluded on the Platform. Flipkart shall not and is not
                    required to mediate or resolve any dispute or disagreement
                    between Buyers and Sellers.
                  </p>
                </li>
                <li>
                  <p>
                    Flipkart does not make any representation or warranty as to
                    the item-specifics (such as legal title, creditworthiness,
                    identity, etc) of any of its Users. You are advised to
                    independently verify the bona fides of any particular User
                    that You choose to deal with on the Platform and use Your
                    best judgment in that behalf.
                  </p>
                </li>
                <li>
                  <p>
                    Flipkart does not at any point of time during any
                    transaction between Buyer and Seller on the Platform come
                    into or take possession of any of the products or services
                    offered by Seller nor does it at any point gain title to or
                    have any rights or claims over the products or services
                    offered by Seller to Buyer.
                  </p>
                </li>
                <li>
                  <p>
                    At no time shall Flipkart hold any right, title or interest
                    over the products nor shall Flipkart have any obligations or
                    liabilities in respect of such contract entered into between
                    Buyers and Sellers. Flipkart is not responsible for
                    unsatisfactory or delayed performance of services or damages
                    or delays as a result of products which are out of stock,
                    unavailable or back ordered.
                  </p>
                </li>
                <li>
                  <p>
                    The Platform is only a platform that can be utilized by
                    Users to reach a larger base to buy and sell products or
                    services. Flipkart is only providing a platform for
                    communication and it is agreed that the contract for sale of
                    any of the products or services shall be a strictly
                    bipartite contract between the Seller and the Buyer.
                  </p>
                </li>
              </ul>
              <p>
                The Platform is only a platform that can be utilized by Users to
                reach a larger base to buy and sell products or services.
                Flipkart is only providing a platform for communication and it
                is agreed that the contract for sale of any of the products or
                services shall be a strictly bipartite contract between the
                Seller and the Buyer.
              </p>
              <p>
                Flipkart is not responsible for unsatisfactory or delayed
                performance of services or damages or delays as a result of
                products which are out of stock, unavailable or back ordered.
              </p>
              <p>
                Select products offered by sellers may be eligible for business
                purchases on the Platform.
              </p>
              <ul>
                <li>
                    <p>Upon Your purchase of product(s) eligible for business purchases, You may be able to avail the benefits of GST input tax credit. Accordingly, at your request, an invoice containing the GSTIN as provided by You ("Tax Invoice") shall be issued to You by the Seller(s) selling such products.</p>
                </li>
                <li>
                    <p>GST invoice will have, inter alia, the following details printed on it: -GSTIN associated with your registered business, as provided by you</p>
                </li>
                <li>
                    <p>Entity name of your registered business, as provided by you</p>
                </li>
                <li>
                    <p>Not all products are eligible for business purchases on the Platform and the same is solely at the discretion of the Sellers. You will be able to view the eligibility of Tax Invoice on the product page on the Platform.</p>
                </li>
                <li>
                    <p>Purchases on the Platform must only be for end consumption. Users must not use products purchased on the Platform for any commercial, promotional, resale or further distribution purposes.</p>
                </li>
                <li>
                    <p>For seamless availment of input tax credit, kindly mention the delivery address as the address which is mentioned as the registered place of business as per the records of GST authority. Please note that availment of input tax credit is subject to provisions of GST Act and rules.
</p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <Subfooter />
    </>
  );
};

export default Termofuse;